# Generated by Django 4.0.5 on 2023-01-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_review_rating_alter_review_tour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
