# Generated by Django 4.1.5 on 2023-01-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='uploaded_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
