# Generated by Django 4.1.5 on 2023-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_review_user_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='user',
        ),
        migrations.AddField(
            model_name='destination',
            name='poster',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
