# Generated by Django 4.1.5 on 2023-03-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('Excursions', 'Excursions'), ('Safari Tours', 'Safari Tours'), ('Farm Tours', 'Farm Tours'), ('Hiking and Adventures Tours', 'Hiking and Adventures Tours')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
