# Generated by Django 4.1.5 on 2023-03-13 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_destination_category_delete_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tour',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
