# Generated by Django 4.1.5 on 2023-03-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tour',
            field=models.CharField(max_length=200),
        ),
    ]
