# Generated by Django 4.1.7 on 2023-04-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_invoice_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='type_payment',
            field=models.CharField(blank=True, choices=[('M-PESA', 'M-PESA'), ('Paypal', 'Paypal'), ('Stripe', 'Stripe')], max_length=200, null=True),
        ),
    ]
