# Generated by Django 4.1.7 on 2023-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_booking_tour_time_destination_tour_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='tour_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
