# Generated by Django 4.1.7 on 2023-04-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_destination_tour_time_booking_tour_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
