# Generated by Django 4.1.7 on 2023-04-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_review', to='base.destination'),
        ),
    ]
