# Generated by Django 4.1.7 on 2023-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_destination_review_review_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
