# Generated by Django 4.1.7 on 2023-04-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_destination_about_alter_destination_itinerary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
