# Generated by Django 4.1.7 on 2023-04-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
