# Generated by Django 4.1.7 on 2023-05-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='booking',
        ),
        migrations.AddField(
            model_name='cart',
            name='booking',
            field=models.ManyToManyField(to='base.booking'),
        ),
    ]
