# Generated by Django 4.1.7 on 2023-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_cart_booking_cart_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='booking',
            field=models.ManyToManyField(related_name='booking', to='base.booking'),
        ),
    ]
