# Generated by Django 4.1.7 on 2023-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_cart_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
