# Generated by Django 4.1.7 on 2023-05-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='discounted_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
