# Generated by Django 4.1.7 on 2023-06-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_remove_booking_paid_cart_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='discounted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
