# Generated by Django 4.1.7 on 2023-06-01 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_destination_discounted_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='likes',
            field=models.ManyToManyField(blank='true', related_name='tour_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
